const GET_CHARACTERS_STATE = {
    GET_CHARACTERS : 'GET_CHARACTERS',
    GET_CHARACTERS_SUCESS : 'GET_CHARACTERS_SUCESS',
    GET_CHARACTERS_ERROR : 'GET_CHARACTERS_ERROR'
}

export default GET_CHARACTERS_STATE