const GET_CHARACTER_STATE = {
    GET_CHARACTER : 'GET_CHARACTER',
    GET_CHARACTER_SUCESS : 'GET_CHARACTER_SUCESS',
    GET_CHARACTER_ERROR : 'GET_CHARACTER_ERROR'
}

export default GET_CHARACTER_STATE